enigme:  enigme.o main.o 
	gcc main.o enigme.o -o enigme -lSDL -lSDL_image -lSDL_mixer  -lSDL_ttf -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
enigme.o:enigme.c
	gcc -c enigme.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g



